# Site settings
title: Kelly Perez
email: Kelly.Perez2@snhu.edu
description: > # this means to ignore newlines until "baseurl:"
  CS 499 ePortfolio
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "http://Noxx12.github.io" # the base hostname & protocol for your site
github_username:  Noxx12



sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
